import { ProtocolConfig } from './types';
import type { EthereumProtocol, L2Protocol } from '../../types';

export const ethereumProtocols: Record<string, ProtocolConfig> = {
  uniswapV2: {
    id: 'uniswap-v2' as EthereumProtocol,
    name: 'Uniswap V2',
    emoji: '🦄',
    color: '#FF007A',
    chain: 'ethereum',
    website: 'https://app.uniswap.org',
    manageUrl: 'https://app.uniswap.org/#/pool',
    subgraphUrl: 'https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2',
    factoryAddress: '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f',
    isActive: true,
    supportedFeatures: {
      v2: true,
      v3: false,
      concentrated: false,
      stable: false,
    },
  },
  uniswapV3: {
    id: 'uniswap-v3' as EthereumProtocol,
    name: 'Uniswap V3',
    emoji: '🦄',
    color: '#FF007A',
    chain: 'ethereum',
    website: 'https://app.uniswap.org',
    manageUrl: 'https://app.uniswap.org/#/pool',
    subgraphUrl: 'https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3',
    factoryAddress: '0x1F98431c8aD98523631AE4a59f267346ea31F984',
    isActive: true,
    supportedFeatures: {
      v2: false,
      v3: true,
      concentrated: true,
      stable: false,
    },
  },
  sushiswap: {
    id: 'sushiswap' as EthereumProtocol,
    name: 'SushiSwap',
    emoji: '🍣',
    color: '#0E4FD6',
    chain: 'ethereum',
    website: 'https://www.sushi.com',
    manageUrl: 'https://www.sushi.com/pool',
    subgraphUrl: 'https://api.thegraph.com/subgraphs/name/sushiswap/exchange',
    factoryAddress: '0xC0AEe478e3658e2610c5F7A4A2E1777cE9e4f2Ac',
    isActive: true,
    supportedFeatures: {
      v2: true,
      v3: true,
      concentrated: true,
      stable: false,
    },
  },
  curve: {
    id: 'curve' as EthereumProtocol,
    name: 'Curve Finance',
    emoji: '🌊',
    color: '#40E0D0',
    chain: 'ethereum',
    website: 'https://curve.fi',
    manageUrl: 'https://curve.fi/#/ethereum/pools',
    apiEndpoint: 'https://api.curve.fi/api',
    isActive: true,
    supportedFeatures: {
      v2: false,
      v3: false,
      concentrated: false,
      stable: true,
    },
  },
  balancer: {
    id: 'balancer' as EthereumProtocol,
    name: 'Balancer',
    emoji: '⚖️',
    color: '#1E1E1E',
    chain: 'ethereum',
    website: 'https://balancer.fi',
    manageUrl: 'https://app.balancer.fi/#/ethereum/pool',
    subgraphUrl: 'https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-v2',
    isActive: true,
    supportedFeatures: {
      v2: true,
      v3: false,
      concentrated: false,
      stable: true,
    },
  },
};

// Layer 2 Extensions (only the ones defined in L2Protocol)
export const l2Protocols: Record<string, ProtocolConfig> = {
  uniswapV3Arbitrum: {
    id: 'uniswap-v3-arbitrum' as L2Protocol,
    name: 'Uniswap V3',
    emoji: '🦄',
    color: '#FF007A',
    chain: 'arbitrum',
    website: 'https://app.uniswap.org',
    manageUrl: 'https://app.uniswap.org/#/pool?chain=arbitrum',
    subgraphUrl: 'https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3-arbitrum',
    factoryAddress: '0x1F98431c8aD98523631AE4a59f267346ea31F984',
    isActive: true,
    supportedFeatures: {
      v2: false,
      v3: true,
      concentrated: true,
      stable: false,
    },
  },
  uniswapV3Polygon: {
    id: 'uniswap-v3-polygon' as L2Protocol,
    name: 'Uniswap V3',
    emoji: '🦄',
    color: '#FF007A',
    chain: 'polygon',
    website: 'https://app.uniswap.org',
    manageUrl: 'https://app.uniswap.org/#/pool?chain=polygon',
    subgraphUrl: 'https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3-polygon',
    factoryAddress: '0x1F98431c8aD98523631AE4a59f267346ea31F984',
    isActive: true,
    supportedFeatures: {
      v2: false,
      v3: true,
      concentrated: true,
      stable: false,
    },
  },
  uniswapV3Base: {
    id: 'uniswap-v3-base' as L2Protocol,
    name: 'Uniswap V3',
    emoji: '🦄',
    color: '#FF007A',
    chain: 'base',
    website: 'https://app.uniswap.org',
    manageUrl: 'https://app.uniswap.org/#/pool?chain=base',
    subgraphUrl: 'https://api.studio.thegraph.com/query/45376/uniswap-v3-base/version/latest',
    factoryAddress: '0x33128a8fC17869897dcE68Ed026d694621f6FDfD',
    isActive: true,
    supportedFeatures: {
      v2: false,
      v3: true,
      concentrated: true,
      stable: false,
    },
  },
};