import { ProtocolConfig } from './types';
import type { SolanaProtocol } from '../../types';

export const solanaProtocols: Record<string, ProtocolConfig> = {
  meteora: {
    id: 'meteora-dlmm' as SolanaProtocol,
    name: 'Meteora DLMM',
    emoji: '☄️',
    color: '#7C2AE8',
    chain: 'solana',
    website: 'https://meteora.ag',
    manageUrl: 'https://meteora.ag/pools',
    apiEndpoint: 'https://dlmm-api.meteora.ag',
    programId: 'LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo',
    isActive: true,
    supportedFeatures: {
      v2: false,
      v3: false,
      concentrated: true,
      stable: false,
    },
  },
  raydium: {
    id: 'raydium-clmm' as SolanaProtocol,
    name: 'Raydium CLMM',
    emoji: '⚡',
    color: '#8C6EEF',
    chain: 'solana',
    website: 'https://raydium.io',
    manageUrl: 'https://raydium.io/clmm/create-position',
    apiEndpoint: 'https://api.raydium.io/v2',
    programId: 'CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK',
    isActive: true,
    supportedFeatures: {
      v2: false,
      v3: true,
      concentrated: true,
      stable: false,
    },
  },
  orca: {
    id: 'orca-whirlpools' as SolanaProtocol,
    name: 'Orca Whirlpools',
    emoji: '🐋',
    color: '#FF6B35',
    chain: 'solana',
    website: 'https://orca.so',
    manageUrl: 'https://www.orca.so/pools',
    apiEndpoint: 'https://api.orca.so',
    programId: 'whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc',
    isActive: true,
    supportedFeatures: {
      v2: false,
      v3: true,
      concentrated: true,
      stable: false,
    },
  },
  lifinity: {
    id: 'lifinity' as SolanaProtocol,
    name: 'Lifinity',
    emoji: '♾️',
    color: '#00D4AA',
    chain: 'solana',
    website: 'https://lifinity.io',
    manageUrl: 'https://lifinity.io/trade',
    apiEndpoint: 'https://api.lifinity.io',
    programId: 'EewxydAPCCVuNEyrVN68PuSYdQ7wKn27V9Gjeoi8dy3S',
    isActive: true,
    supportedFeatures: {
      v2: true,
      v3: false,
      concentrated: false,
      stable: false,
    },
  },
  jupiter: {
    id: 'jupiter' as SolanaProtocol,
    name: 'Jupiter',
    emoji: '🪐',
    color: '#FBA43A',
    chain: 'solana',
    website: 'https://jup.ag',
    manageUrl: 'https://jup.ag/perps-pools',
    apiEndpoint: 'https://api.jup.ag',
    programId: 'JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4',
    isActive: true,
    supportedFeatures: {
      v2: false,
      v3: false,
      concentrated: true,
      stable: false,
    },
  },
};